### ISSUE TITLE
naming

### ISSUE THREAD

**Issue by celesteking** [CpanelInc/ea-php74#1]
Why is this repo named `ea-php74` while previous were named `scl-php*` ?

**Comment by drmuey** [comment]
That is a great question @celesteking ! While the git repo name is essentially arbitrary, there were a  couple reasons for the deviation:

1. It made it consistent w/ a conceptual type of SCL that we have that use a `macros/` directory w/ the idea we’d that we’d rename the others ot match.
2. It made some tooling simpler

That said, if its causing a problem it’d be easy enough to rename it and update the tooling to match.

Is there a particular problem is caused you?

**Comment by celesteking** [comment]
It's not causing any problem so far,  I just noticed the inconsistency between old repo names and this repo name, that's all. Thankfully, we don't depend on name consistency in our CI builds as we've got a separate build config per repo. just make sure not to rename it out of the blue as that might wreak havoc.
