### ISSUE TITLE
stale repo

### ISSUE THREAD

**Issue by celesteking** [CpanelInc/ea-php74#3]
You've pushed http://208.100.0.204/cpanelsync/repos/CentOS/7/EA4/x86_64/ea-php74-7.4.18-1.1.1.cpanel.x86_64.rpm , but you haven't updated this repo.  What's the problem? Thanks.

**Comment by gitcory** [comment]
Hello, my apologies I had missed that it didn't update. I have updated the production branch at this time. There is an issue with the master branch that I am working on now. I'll update here once that is also fixed. Thank you for opening this issue and bringing this to our attention.

**Comment by gitcory** [comment]
Okay, this is now fixed in master as well. You will notice it is 7.4.19 as we are in the middle of updating to that version. It is simply a revert from upstream PHP for PDO_pgsql bug that was introduced in 7.4.18. Otherwise it is identical to our release of 7.4.18. Thanks again for your report.

**Comment by celesteking** [comment]
nbd, we're tracking production branch. tnx.
